module.exports = {
  p1: "Us preguem Senyor, per les famílies cristianes, perquè siguin “església domèstica” on puguin néixer futures vocacions per a l’Església universal.",
  p2: "Perquè els joves de la nostra comunitat estiguin sempre oberts a Déu, i disposats a seguir-lo dedicant tota la seva vida al servei de l’Evangeli i de l’Església.",
  p3: "Vesseu Senyor el vostre Esperit sobre molts joves, perquè sentint l’amor tan gran amb què els crideu, vulguin oferir la seva vida per servir-vos com a ministres de la vostra misericòrdia.",
  p4: "Perquè Déu concedeixi a l’Església abundància de vocacions a la vida sacerdotal i religiosa.",
  p5: "Envieu apòstols que portin el vostre sant Nom a tots els racons d’aquesta nostra diòcesi.",
  p6: "Perquè els seminaristes de la nostra diòcesi i de tota l’Església avancin cap al sacerdoci amb un estudi seriós, una pietat sincera i una entrega generosa.",
  p7: "Perquè Déu Totpoderós susciti en l’Església les vocacions necessàries per al millor servei del Poble de Déu.",
  p8: "Guardeu Senyor en aquest nou dia als preveres, ministres de l’Església i als seminaristes; feu que la seva fidelitat i el seu exemple serveixin de testimoni i crida per a molts joves.",
  p9: "Perquè mai faltin a l’Església universal i a la nostra diòcesi ministres de Crist, dispensadors dels ministeris de Déu.",
  p10: "Perquè Jesucrist, el Bon Pastor, susciti entre els joves cristians sacerdots que el facin present en el món, tal necessitat de bons pastors que estimin i donin la vida per les ovelles.",
  p11: "Perquè en el si de les famílies cristianes hi hagi un clima de pietat, de treball, de generositat, que afavoreixi la descoberta i creixement de la vocació particular de cada fill i de cada filla.",
  p12: "Perquè Crist, el Gran Sacerdot, ajudi els joves a descobrir la grandesa i la urgència de la vocació sacerdotal per a la salvació del món.",
  p13: "Perquè la vida entregada i joiosa dels qui s’han consagrat a Déu en la vida sacerdotal i religiosa sigui un reclam per a tants nois i noies encara indecisos en la seva vocació.",
  p14: "Envieu apòstols que portin el nostre sant Nom a tots els racons d’aquesta nostra diòcesi de Terrassa.",
  p15: "Perquè Déu nostre Senyor confirmi en la generositat aquells que ha cridat al sacerdoci o la vida consagrada.",
  p16: "Us demanem Senyor que crideu molts joves a ser imatges vives de Jesucrist Bon Pastor, que manifestin la vostra misericòrdia a la vostra Església i al nostre món.",
  p17: "Us preguem Senyor pels infants i joves que s’estan formants en els Seminaris Menors, Majors i els Noviciats: feu que sempre vulguin servir Crist en els germans més pobres.",
  p18: "Perquè Déu, l’Amo dels sembrats, hi enviï abundància de segadors, especialment en aquelles diòcesis del món més mancades.",
  p19: "Perquè hi hagi molts joves que, fixa la mirada i el cor en Jesús, consagrin tota la seva vida a estendre el seu amor i el seu missatge de salvació.",
  p20: "Perquè el Senyor, que escollí un estil de vida virginal i pobre, susciti en els joves de les nostres comunitats el desig de consagrar-se exclusivament al seu amor i al servei de la seva Església.",
  p21: "Que els joves que vós crideu, Senyor, no siguin com el jove ric, sinó que, interpel·lats per la vostra mirada d’amor, no dubtin a deixar-ho tot per seguir-vos.",
  p22: "Perquè els joves comprenguin que escampar el missatge de l’Evangeli arreu del món és la necessitat més urgent del nostre temps i una vocació que omplirà de joia i sentit la seva vida.",
  p23: "Perquè el Senyor il·lumini la ment dels joves cristians i els infongui la seva força perquè siguin molts els qui es lliurin al ministeri sacerdotal.",
  p24: "Perquè Déu Totpoderós esculli joves de la nostra diòcesi que, deixant els béns d’aquest món, es consagrin del tot al servei del Regne de Déu.",
  p25: "Perquè els joves cristians, vivint amb profunditat la gràcia del Baptisme, es preguntin quina és la voluntat de Déu sobre la seva vida i la segueixin amb decisió.",
  p26: "Perquè hi hagi molts nois i noies que acullin la crida de Déu a consagrar-se plenament al servei de l’Evangeli, de l’Església i del món.",
  p27: "Guardeu, Senyor, en aquest nou dia als preveres, ministres de l’Església i als seminaristes; feu que la seva fidelitat i el seu exemple serveixin de testimoni i crida per a molts joves.",
  p28: "Perquè Crist, el Gran Sacerdot, ajudi els joves a descobrir la grandesa i la urgència de la vocació sacerdotal per la salvació del món.",
  p29: "Envieu-nos Senyor els guies espirituals que necessitem: autèntics sacerdots del Déu viu que, il·luminats per la vostra Paraula, sàpiguen parlar de Vós i ensenyin a parlar amb Vós.",
  p30: "Doneu-nos, Senyor, el do de les vocacions al sacerdoci que la vostra Església necessita.",
  p31: "Perquè el Senyor vessi en les famílies cristianes l’esperit de pietat amb què hi germinin nombroses vocacions al servei de l’Església.",
  p32: "Perquè Crist, que va reunir les deixebles al seu voltant per associar-los a la seva predicació evangèlica, susciti en els nostres dies servidors del seu Evangeli.",
  p33: "Déu misericordiós, que vau donar el vostre Fill únic per salvar tots els homes, infoneu la vostra generositat en el cor dels pares cristians perquè amb goig i alegria recolzin la crida dels seus fills.",
};
